f = open('broadcast_2017_01_03.captions.txt', 'rt', encoding = 'UTF-8')
new_f = open('broadcast_2017_01_03.captions_u.txt', 'wt', encoding = 'UTF-8')
l = f.readlines()
s = set(l)
l = list(s)
l.sort(key=len)
new_f.writelines(l)